<a href="https://colab.research.google.com/github/danielduartt/Numpy-Python/blob/main/M%C3%A9todos%20e%20M%C3%A1scaras/M%C3%A9todos_e_M%C3%A1scaras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#**Métodos importantes**



01.   ndim
02.   shape
3.   dtype
4. astype
5. min
6. max
7. argmin
8. sum
9. mean
10. var
11. std
12. sort
13. T
14. reshape



In [13]:
#1. ndim
arr = np.random.randn(10)
print(arr)
print(arr.ndim)# retorna a dimensão do array

[ 0.19398765 -0.1515257  -0.572619   -0.32791278 -1.19888005  1.03415857
  1.95332692  0.91546905  0.33476867  0.24536084]
1


In [25]:
#2. shap
print(arr.shape)# retorna o formato do array => (10, 1) 10 elementos e 1 linha


(10,)


In [26]:
#3. dtype
arr.dtype #retorna o tipo de dado

dtype('int32')

In [23]:
#4. astype
arr = arr.astype(np.int32) # pode colocar 'int' no lugar de np.int32, int como string mesmo
arr.dtype

dtype('int32')

In [30]:
#5. min, retorna o menor valor
arr2 = np.random.randint(0,20, size = (3,3))
print(arr2)
print(arr2.min())

[[13 17 19]
 [16 15  5]
 [13  3  8]]
3


In [31]:
#6. max, retorna o maior valor
arr2.max()

19

In [34]:
#7. argmin ou argmax, retorna o indice do menor e do maior elemento
print(arr2.argmax())
print(arr2.argmin())

2
7


In [48]:
#8. mean => média
#9 sum => soma
#10 var => variancia
#11 std => desvio padrão
print(f"Média {np.mean(arr2):.2f}") #arr2.mean()
print(f"Soma {arr2.sum()}")
print(f"Variância {np.var(arr2):.2f}") #arr2.var()
print(f"DP {np.std(arr2):.2f}") #arr2.std()

Média 12.11
Soma 109
Variância 27.43
DP 5.24


In [52]:
#12. sort, ordenação so array
arr2.sort() #crescente em cada linhas
print(arr2)


[[13 17 19]
 [ 5 15 16]
 [ 3  8 13]]


In [53]:
#13. T => transposta de uma matriz
arr2.T

array([[13,  5,  3],
       [17, 15,  8],
       [19, 16, 13]])

#**Máscaras**
array booleano definindo quais serão os elementos que serão escolhidos em outro array

In [59]:
a = np.array([1,2,3,4])#quero só 3 e 4
print(a[2:])
print("-----------Usando Máscaras-----------")
a[[False, False, True, True]] #Máscara, forma I


[3 4]
-----------Usando Máscaras-----------


array([3, 4])

In [64]:
a >= 3 #Máscara, forma II
print(a[a >= 3])
print(a[a % 2 == 0 ])

[3 4]
[2 4]
