<a href="https://colab.research.google.com/github/danielduartt/Numpy-Python/blob/main/Opera%C3%A7%C3%B5es%20com%20Matrizes/Operacoes_Em_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#**Com escalares**

In [2]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
arr = 10 * arr
print(arr)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [13]:
arr2 = np.random.randint(0, 10, size = (2,3))
print(arr2)
print('--------------------')
print(arr2 / 2)


[[9 4 0]
 [1 9 0]]
--------------------
[[4.5 2.  0. ]
 [0.5 4.5 0. ]]


In [23]:
np.random.seed(32) #faz com que os números criados aleatórios se mantenham
print(arr2)
print('--------------------')
print(arr2 - 2) #subtraindo -2 de todos os elementos

[[9 4 0]
 [1 9 0]]
--------------------
[[ 7  2 -2]
 [-1  7 -2]]


#**Entre Arrays**

In [27]:
arr2 = np.random.randint(1, 100, 8)
arr3 = np.random.randint(1, 100, 8) # 8 elementos
print(arr3)
print('-----------------------------------')
print(arr2 + arr3) # so vai poder somar se tiverem o mesmo tamanho
#o shapes podem ser diferentes se for multiplicação de matrizes
print('-----------------------------------')
print(arr2 * arr3) #está multiplicando elemento a elemento, não é uma multiplicação de matrizes

[62 51 46 25 12 94 48 44]
-----------------------------------
[131 114  77 106  96 145 123  80]
-----------------------------------
[4278 3213 1426 2025 1008 4794 3600 1584]


In [36]:
#---------------------  Multiplicação de Matrizes -----------------------
#(3 x 2) x (2 x 3) = (3 x 3) => para poder fazer a mult de matrizes é necessário
# que a matriz A tenha a quantidade de linhas iguais a quantidade de colunas da matriz B
m1 = np.random.randint(1, 10, size = (3, 2))
print("--------------Matriz A----------------")
print(m1)
print("--------------Matriz B----------------")
m2 = np.random.randint(1, 10, size = (2, 3))
print(m2)
print("---------------A x B------------------")
m3 = m1.dot(m2)
print(m3)


--------------Matriz A----------------
[[5 5]
 [6 7]
 [9 5]]
--------------Matriz B----------------
[[1 7 5]
 [1 4 3]]
---------------A x B------------------
[[10 55 40]
 [13 70 51]
 [14 83 60]]


#**Comparações**

In [42]:
arr1 = np.array([1,2,2,1])
arr2 = np.array([3,2,3,1])
print(arr1 == arr2)
#Comparando o array todo
print('---------------------------')
np.array_equal(arr1, arr2)

[False  True False  True]
---------------------------


False