<a href="https://colab.research.google.com/github/danielduartt/Numpy-Python/blob/main/Exerc%C3%ADcios_Fixa%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


#**Exercício Numpy**





* Exercício 1: Crie um array NumPy com os números de 1 a 10 e imprima-o.

In [2]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


* Exercício 2: Crie um array NumPy com 10 elementos, todos iguais a 5.

In [3]:
arr = np.full(10, 5) # 10 elementos, todos iguais a zero            >IMPORTANTE!<
print(arr)

[5 5 5 5 5 5 5 5 5 5]


* Exercício 3: Crie um array NumPy com os números pares de 0 a 50.

In [4]:
arr = np.arange(0, 51, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]


* Exercício 4: Crie um array NumPy com os números ímpares de 1 a 50.

In [7]:
array = np.arange(1, 51, 2)
print(array)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


* Exercício 5: Crie um array NumPy com 25 elementos aleatórios, com valores entre 0 e 100.

In [9]:
random_arr = np.random.randint(0, 100, 25)
print(random_arr)

[69 29 89 51 11 55 10 90 66  4 44 56 21 67 91 38 51 53 19 74 26 15  1  3
 24]


* Exercício 6: Dado o array NumPy [1, 2, 3, 4, 5], inverta a ordem dos elementos.

In [18]:
arr = np.array([1,2,3,4,5])
arr = arr[-1::-1]
print(arr)

[5 4 3 2 1]


* Exercício 7: Dado o array NumPy [1, 2, 3, 4, 5], crie um novo array com os elementos em ordem inversa, mas mantendo o original inalterado.

In [19]:
arr_original = np.array([1,2,3,4,5])
arr_inverso = arr_original[-1::-1]
print("------------Original---------------")
print(arr_original)
print("------------Inverso----------------")
print(arr_inverso)


------------Original---------------
[1 2 3 4 5]
------------Inverso----------------
[5 4 3 2 1]


* Exercício 8: Crie um array NumPy bidimensional 3x3 com valores de 0 a 8.

In [22]:
arr_3x3 = np.arange(9).reshape(3,3) #IMPORTANTE!
print(arr_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


* Exercício 9: Crie um array NumPy bidimensional 5x5 com valores aleatórios entre 0 e 9. Em seguida, encontre o valor máximo e o valor mínimo do array

In [36]:
arr_5x5_ale = np.random.randint(0, 10, size = (5,5)) #IMPORTANTE!
print(arr_5x5_ale)
print("Maior valor: ", arr_5x5_ale.max())
print("Menor valor: ", arr_5x5_ale.min())

[[4 4 3 8 9]
 [0 1 9 9 6]
 [4 1 2 2 5]
 [2 7 9 6 6]
 [3 3 3 5 8]]
Maior valor:  9
Menor valor:  0


* Exercício 10: Dado o array NumPy [1, 2, 3, 4, 5], substitua todos os valores maiores que 3 por 0.

In [37]:
arr = np.array([1,2,3,4,5])
arr[arr > 3] = 0
print(arr)

[1 2 3 0 0]


* Exercício 11: Dado o array NumPy [1, 2, 3, 4, 5], crie um novo array com os quadrados de cada elemento.

In [39]:
arr = np.array([1,2,3,4,5])
arr = arr[:]**2
print(arr)
# Ou
arr2 =  np.array([1,2,3,4,5])
arr2 =  np.square(arr2) #IMPORTANTE!
print(arr2)


[ 1  4  9 16 25]
[ 1  4  9 16 25]


* Exercício 12: Dado o array NumPy [1, 2, 3, 4, 5], calcule a média dos elementos.

In [40]:
arr = np.array([1,2,3,4,5])
print(f"Média: {arr.mean()}")

Média: 3.0


* Exercício 13: Dado o array NumPy [1, 2, 3, 4, 5], normalize os valores de forma que a soma seja igual a 1.

In [44]:
arr = np.array([1,2,3,4,5])
arr_normalizado = arr / arr.sum()
print(arr_normalizado)
print(f"Soma do array {arr_normalizado.sum()}")

[0.06666667 0.13333333 0.2        0.26666667 0.33333333]
Soma do array 1.0


* Exercício 14: Crie um array NumPy com 10 elementos aleatórios entre 0 e 1. Em seguida, arredonde os valores para o inteiro mais próximo.

In [51]:
arr = np.random.randn(10)
print("Original: ", arr)
arr_arredondado = arr.astype(np.int32)
print(f"Arredondado: {arr_arredondado}")
#                 OU
print("------------------------------------")
array14 = np.random.random(10)
print(array14)
array14_arredondado = np.round(array14)
print(array14_arredondado)


Original:  [-2.04927529  1.34405167  0.10547473 -0.65013728  0.65304466  0.27510326
 -1.19274038 -0.90017915 -0.15704605  0.23767727]
Arredondado: [-2  1  0  0  0  0 -1  0  0  0]
------------------------------------
[-2.  1.  0. -1.  1.  0. -1. -1. -0.  0.]
------------------------------------
[0.91456725 0.94926884 0.11498365 0.22101073 0.23196432 0.09945341
 0.33821642 0.87361414 0.87822066 0.52211495]
[1. 1. 0. 0. 0. 0. 0. 1. 1. 1.]


* Exercício 15: Dado o array NumPy [1, 2, 3, 4, 5], verifique se algum dos elementos é maior que 3.

In [52]:
arr = np.array([1,2,3,4,5])
maiores_que_3 = arr[arr > 3]
print(maiores_que_3)

[4 5]
