<a href="https://colab.research.google.com/github/danielduartt/Numpy-Python/blob/main/Exerc%C3%ADcio_Fixa%C3%A7%C3%A3o_2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#**Exercício Numpy**
Exercício 1:



* Exercício 1: Crie um array NumPy unidimensional com os números de 0 a 9. Acesse o primeiro elemento do array.

In [2]:
arr1 = np.arange(0, 10)
print(arr1[0])

0


* Exercício 2: Crie um array NumPy unidimensional com os números de 0 a 9. Acesse o último elemento do array.

In [3]:
arr2 = np.arange(10)
print(arr2[-1])

9


* Exercício 3: Crie um array NumPy unidimensional com os números de 0 a 9. Acesse os elementos do índice 2 ao índice 5 (inclusivo).

In [6]:
arr3 = np.arange(10)
print(arr3[2: 6])

[2 3 4 5]


* Exercício 4: Crie um array NumPy unidimensional com os números de 0 a 9. Acesse os elementos do índice 5 até o final do array.

In [7]:
arr4 = np.arange(10)
print(arr4[5:])

[5 6 7 8 9]


* Exercício 5: Crie um array NumPy bidimensional 3x3 com valores de 0 a 8. Acesse o elemento da segunda linha e terceira coluna.

In [17]:
arr5 = np.arange(9).reshape(3,3)
print(arr5)
print(f"[2,3]: {arr5[1][2]}")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2,3]: 5


* Exercício 6: Crie um array NumPy bidimensional 3x3 com valores de 0 a 8. Acesse a primeira coluna inteira.

In [19]:
arr6 = np.arange(9).reshape(3, 3)
print(arr6)
print("--------------primeira coluna----------------")
print(arr6[:, 0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------primeira coluna----------------
[0 3 6]


* Exercício 7: Crie um array NumPy bidimensional 3x3 com valores de 0 a 8. Acesse a última linha inteira.

In [20]:
arr7 = np.arange(9).reshape(3,3)
print(arr7)
print("--------------última coluna----------------")
print(arr7[:, -1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------última coluna----------------
[2 5 8]


* Exercício 8: Crie um array NumPy bidimensional 4x4 com valores aleatórios entre 0 e 9. Acesse a submatriz formada pelas duas primeiras linhas e duas primeiras colunas.

In [32]:
arr8 = np.random.randint(0,10, size = (4, 4))
print(arr8)
print("-------------Resposta------------")
print(arr8[0:2, 0:2])

[[4 2 2 3]
 [5 3 1 1]
 [6 8 3 9]
 [1 8 5 9]]
-------------Resposta------------
[[4 2]
 [5 3]]


* Exercício 9: Crie um array NumPy bidimensional 4x4 com valores aleatórios entre 0 e 9. Acesse a diagonal principal da matriz.

In [33]:
arr9 = np.random.randint(0, 10, size = (4,4))
print(arr9)
print("-------------Resposta------------")
print(np.diag(arr9)) #IMPORTANTE!

[[6 5 6 5]
 [2 1 8 1]
 [4 1 0 9]
 [7 9 9 6]]
-------------Resposta------------
[6 1 0 6]


* Exercício 10: Crie um array NumPy bidimensional 4x4 com valores aleatórios entre 0 e 9. Acesse todos os elementos da segunda coluna.

In [36]:
arr10 = np.random.randint(0, 10, size = (4,4))
print(arr10)
print("-------------Resposta------------")
print(arr10[:, 1])

[[3 4 7 1]
 [6 2 9 7]
 [4 6 5 2]
 [2 7 4 3]]
-------------Resposta------------
[4 2 6 7]


* Exercício 11: Crie um array NumPy unidimensional com os números de 1 a 10. Acesse apenas os elementos que são maiores que 5.

In [40]:
arr11 = np.arange(1, 11)
print(arr1)
print("-------------Resposta------------")
print(arr11[arr11 > 5])


[0 1 2 3 4 5 6 7 8 9]
-------------Resposta------------
[ 6  7  8  9 10]


* Exercício 12: Crie um array NumPy unidimensional com os números de 1 a 10. Substitua os elementos menores que 5 por 0.

In [41]:
arr12 = np.arange(1, 11)
print(arr12)
print("-------------Resposta------------")
arr12[arr12 > 5] = 0
print(arr12)

[ 1  2  3  4  5  6  7  8  9 10]
-------------Resposta------------
[1 2 3 4 5 0 0 0 0 0]


* Exercício 13: Crie um array NumPy unidimensional com valores aleatórios entre 0 e 9. Crie um novo array contendo apenas os elementos únicos do array original.

In [51]:
arr13_ale = np.random.randint(0, 10, 10)
print(arr13_ale)
print("-------------Resposta------------")
arr13_unico = np.unique(arr13_ale)
print(arr13_unico)

[2 6 0 5 8 2 1 2 4 5]
-------------Resposta------------
[0 1 2 4 5 6 8]


* Exercício 14: Crie um array NumPy unidimensional com valores aleatórios entre 0 e 9. Conte a quantidade de ocorrências de cada elemento no array.

In [52]:
array14 = np.random.randint(0,10,10)
unique_elements, counts = np.unique(array14, return_counts=True) #IMPORTANTE!
print(dict(zip(unique_elements, counts)))

{0: 2, 3: 1, 4: 2, 5: 1, 6: 2, 8: 2}


* Exercício 15: Crie um array NumPy unidimensional com valores aleatórios entre 0 e 9. Verifique se o número 5 está presente no array.

In [62]:
arr15 = np.random.randint(0,10,10)
if 5 in arr15:
  print(f"O número 5 está no array: {arr15}")
else:
  print(f"O número 5 não está no array: {arr15}")

O número 5 está no array: [1 2 9 4 7 3 6 0 5 7]
